apiVersion: v1
kind: Service
metadata:
  name: demo-app-svc1
spec:
  selector:
    app: demo-app-svc1
  ports:
    - name: http
      port: 80
      targetPort: 8081
    - name: https
      port: 443
      targetPort: 8081
